IF EXISTS (SELECT 1 FROM sys.tables WHERE name LIKE 'Manufacturer')
DROP TABLE [dbo].[Manufacturer]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Manufacturer](
	[ManufacturerId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](256) NOT NULL,
	[CountryId] [int] NULL,
 CONSTRAINT [PK_Manufacturer] PRIMARY KEY CLUSTERED 
([ManufacturerId] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE UNIQUE NONCLUSTERED INDEX [IDX_Manufacturer_Name_Country] ON [dbo].[Manufacturer]
([Name] ASC,[CountryId] ASC)
INCLUDE ([ManufacturerId]) 
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

IF EXISTS (SELECT 1 FROM sys.tables WHERE name LIKE 'Country')
DROP TABLE [dbo].[Country]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Country](
	[CountryId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](256) NOT NULL,
	[Abbreviation] [nvarchar](10) NULL,
 CONSTRAINT [PK_Country] PRIMARY KEY CLUSTERED 
([CountryId] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

IF EXISTS (SELECT 1 FROM sys.tables WHERE name LIKE 'Model')
DROP TABLE [dbo].[Model]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Model](
	[ModelId] [int] IDENTITY(1,1) NOT NULL,
	[ManufacturerId] [int] NOT NULL,
	[Name] [nvarchar](256) NOT NULL,
	[Year] [int] NOT NULL,
	[PulseMultiplier] decimal(6,3) NULL,
	[PulsePerRev] decimal(6,3) NULL
 CONSTRAINT [PK_Model] PRIMARY KEY CLUSTERED 
([ModelId] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE UNIQUE NONCLUSTERED INDEX [IDX_Model_ManufacturerId_Name_Year] ON [dbo].[Model]
([ManufacturerId] ASC,[Name] ASC,[Year] ASC)
INCLUDE ([ModelId]) 
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

IF EXISTS (SELECT 1 FROM sys.tables WHERE name LIKE 'ThrottleSetPoint')
DROP TABLE [dbo].[ThrottleSetPoint]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ThrottleSetPoint](
	[ThrottleSetPointId] [int] IDENTITY(1,1) NOT NULL,
	[ThrottleSetPointChartId] [int] NOT NULL,
	[Speed] [int] NOT NULL,
	[Gear] [int] NOT NULL,
	[Acceleration] [decimal](6,3) NOT NULL,
	[SetPoint] [decimal](6,3) NOT NULL,
 CONSTRAINT [PK_ThrottleSetPoint] PRIMARY KEY CLUSTERED 
([ThrottleSetPointId] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

IF EXISTS (SELECT 1 FROM sys.tables WHERE name LIKE 'ThrottleSetPointChart')
DROP TABLE [dbo].[ThrottleSetPointChart]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ThrottleSetPointChart](
	[ThrottleSetPointChartId] [int] IDENTITY(1,1) NOT NULL,
	[ModelId] [int] NOT NULL,
	[Name] [nvarchar](256) NOT NULL,
	[Status] [int] NOT NULL,
	[CreationDateTime] [datetime] NOT NULL
 CONSTRAINT [PK_ThrottleSetPointChart] PRIMARY KEY CLUSTERED 
([ThrottleSetPointChartId] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


IF EXISTS (SELECT 1 FROM sys.tables WHERE name LIKE 'RoadTestPoint')
DROP TABLE [dbo].[RoadTestPoint]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RoadTestPoint](
	[RoadTestPointId] [int] IDENTITY(1,1) NOT NULL,
	[RoadTestChartId] [int] NOT NULL,
	[SecondFromStart] [decimal](6,3) NOT NULL,
	[Speed] [decimal](6, 3) NOT NULL
CONSTRAINT [PK_RoadTestPoint] PRIMARY KEY CLUSTERED 
(
	[RoadTestPointId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


IF EXISTS (SELECT 1 FROM sys.tables WHERE name LIKE 'RoadTestChart')
DROP TABLE [dbo].[RoadTestChart]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RoadTestChart](
	[RoadTestChartId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](256) NOT NULL,
	[Status] [int] NOT NULL,
	[CreationDateTime] [datetime] NOT NULL
 CONSTRAINT [PK_RoadTestChart] PRIMARY KEY CLUSTERED 
([RoadTestChartId] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


IF EXISTS (SELECT 1 FROM sys.tables WHERE name LIKE 'GearRatio')
DROP TABLE [dbo].[GearRatio]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GearRatio](
	[GearRatioId] [int] IDENTITY(1,1) NOT NULL,
	[ModelId] [int] NOT NULL,
	[Gear] [int] NOT NULL,
	[Ratio] [decimal](6,3) NOT NULL,
 CONSTRAINT [PK_GearRatio] PRIMARY KEY CLUSTERED 
([GearRatioId] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO