TRUNCATE TABLE Country
GO
INSERT INTO Country VALUES ('Afghanistan', 'AF')
INSERT INTO Country VALUES ('Albania', 'AL')
INSERT INTO Country VALUES ('Algeria', 'DZ')
INSERT INTO Country VALUES ('American Samoa', 'AS')
INSERT INTO Country VALUES ('Andorra', 'AD')
INSERT INTO Country VALUES ('Angola', 'AO')
INSERT INTO Country VALUES ('Anguilla', 'AI')
INSERT INTO Country VALUES ('Antarctica', 'AQ')
INSERT INTO Country VALUES ('Antigua and Barbuda', 'AG')
INSERT INTO Country VALUES ('Argentina', 'AR')
INSERT INTO Country VALUES ('Armenia', 'AM')
INSERT INTO Country VALUES ('Aruba', 'AW')
INSERT INTO Country VALUES ('Australia', 'AU')
INSERT INTO Country VALUES ('Austria', 'AT')
INSERT INTO Country VALUES ('Azerbaijan', 'AZ')
INSERT INTO Country VALUES ('Bahamas', 'BS')
INSERT INTO Country VALUES ('Bahrain', 'BH')
INSERT INTO Country VALUES ('Bangladesh', 'BD')
INSERT INTO Country VALUES ('Barbados', 'BB')
INSERT INTO Country VALUES ('Belarus', 'BY')
INSERT INTO Country VALUES ('Belgium', 'BE')
INSERT INTO Country VALUES ('Belize', 'BZ')
INSERT INTO Country VALUES ('Benin', 'BJ')
INSERT INTO Country VALUES ('Bermuda', 'BM')
INSERT INTO Country VALUES ('Bhutan', 'BT')
INSERT INTO Country VALUES ('Bolivia', 'BO')
INSERT INTO Country VALUES ('Bosnia and Herzegovina', 'BA')
INSERT INTO Country VALUES ('Botswana', 'BW')
INSERT INTO Country VALUES ('Bouvet Island', 'BV')
INSERT INTO Country VALUES ('Brazil', 'BR')
INSERT INTO Country VALUES ('British Indian Ocean Territory', 'IO')
INSERT INTO Country VALUES ('Brunei Darussalam', 'BN')
INSERT INTO Country VALUES ('Bulgaria', 'BG')
INSERT INTO Country VALUES ('Burkina Faso', 'BF')
INSERT INTO Country VALUES ('Burundi', 'BI')
INSERT INTO Country VALUES ('Cambodia', 'KH')
INSERT INTO Country VALUES ('Cameroon', 'CM')
INSERT INTO Country VALUES ('Canada', 'CA')
INSERT INTO Country VALUES ('Cape Verde', 'CV')
INSERT INTO Country VALUES ('Cayman Islands', 'KY')
INSERT INTO Country VALUES ('Central African Republic', 'CF')
INSERT INTO Country VALUES ('Chad', 'TD')
INSERT INTO Country VALUES ('Chile', 'CL')
INSERT INTO Country VALUES ('China', 'CN')
INSERT INTO Country VALUES ('Christmas Island', 'CX')
INSERT INTO Country VALUES ('Cocos (Keeling) Islands', 'CC')
INSERT INTO Country VALUES ('Colombia', 'CO')
INSERT INTO Country VALUES ('Comoros', 'KM')
INSERT INTO Country VALUES ('Congo', 'CG')
INSERT INTO Country VALUES ('Cook Islands', 'CK')
INSERT INTO Country VALUES ('Costa Rica', 'CR')
INSERT INTO Country VALUES ('Cote D''Ivoire (Ivory Coast)', 'CI')
INSERT INTO Country VALUES ('Croatia (Hrvatska)', 'HR')
INSERT INTO Country VALUES ('Cuba', 'CU')
INSERT INTO Country VALUES ('Cyprus', 'CY')
INSERT INTO Country VALUES ('Czech Republic', 'CZ')
INSERT INTO Country VALUES ('Czechoslovakia (former)', 'CS')
INSERT INTO Country VALUES ('Denmark', 'DK')
INSERT INTO Country VALUES ('Djibouti', 'DJ')
INSERT INTO Country VALUES ('Dominica', 'DM')
INSERT INTO Country VALUES ('Dominican Republic', 'DO')
INSERT INTO Country VALUES ('East Timor', 'TP')
INSERT INTO Country VALUES ('Ecuador', 'EC')
INSERT INTO Country VALUES ('Egypt', 'EG')
INSERT INTO Country VALUES ('El Salvador', 'SV')
INSERT INTO Country VALUES ('Equatorial Guinea', 'GQ')
INSERT INTO Country VALUES ('Eritrea', 'ER')
INSERT INTO Country VALUES ('Estonia', 'EE')
INSERT INTO Country VALUES ('Ethiopia', 'ET')
INSERT INTO Country VALUES ('Falkland Islands (Malvinas)', 'FK')
INSERT INTO Country VALUES ('Faroe Islands', 'FO')
INSERT INTO Country VALUES ('Fiji', 'FJ')
INSERT INTO Country VALUES ('Finland', 'FI')
INSERT INTO Country VALUES ('France', 'FR')
INSERT INTO Country VALUES ('France, Metropolitan', 'FX')
INSERT INTO Country VALUES ('French Guiana', 'GF')
INSERT INTO Country VALUES ('French Polynesia', 'PF')
INSERT INTO Country VALUES ('French Southern Territories', 'TF')
INSERT INTO Country VALUES ('Gabon', 'GA')
INSERT INTO Country VALUES ('Gambia', 'GM')
INSERT INTO Country VALUES ('Georgia', 'GE')
INSERT INTO Country VALUES ('Germany', 'DE')
INSERT INTO Country VALUES ('Ghana', 'GH')
INSERT INTO Country VALUES ('Gibraltar', 'GI')
INSERT INTO Country VALUES ('Great Britain (UK)', 'GB')
INSERT INTO Country VALUES ('Greece', 'GR')
INSERT INTO Country VALUES ('Greenland', 'GL')
INSERT INTO Country VALUES ('Grenada', 'GD')
INSERT INTO Country VALUES ('Guadeloupe', 'GP')
INSERT INTO Country VALUES ('Guam', 'GU')
INSERT INTO Country VALUES ('Guatemala', 'GT')
INSERT INTO Country VALUES ('Guinea', 'GN')
INSERT INTO Country VALUES ('Guinea-Bissau', 'GW')
INSERT INTO Country VALUES ('Guyana', 'GY')
INSERT INTO Country VALUES ('Haiti', 'HT')
INSERT INTO Country VALUES ('Heard and McDonald Islands', 'HM')
INSERT INTO Country VALUES ('Honduras', 'HN')
INSERT INTO Country VALUES ('Hong Kong', 'HK')
INSERT INTO Country VALUES ('Hungary', 'HU')
INSERT INTO Country VALUES ('Iceland', 'IS')
INSERT INTO Country VALUES ('India', 'IN')
INSERT INTO Country VALUES ('Indonesia', 'ID')
INSERT INTO Country VALUES ('Iran', 'IR')
INSERT INTO Country VALUES ('Iraq', 'IQ')
INSERT INTO Country VALUES ('Ireland', 'IE')
INSERT INTO Country VALUES ('Israel', 'IL')
INSERT INTO Country VALUES ('Italy', 'IT')
INSERT INTO Country VALUES ('Jamaica', 'JM')
INSERT INTO Country VALUES ('Japan', 'JP')
INSERT INTO Country VALUES ('Jordan', 'JO')
INSERT INTO Country VALUES ('Kazakhstan', 'KZ')
INSERT INTO Country VALUES ('Kenya', 'KE')
INSERT INTO Country VALUES ('Kiribati', 'KI')
INSERT INTO Country VALUES ('Korea (North)', 'KP')
INSERT INTO Country VALUES ('Korea (South)', 'KR')
INSERT INTO Country VALUES ('Kuwait', 'KW')
INSERT INTO Country VALUES ('Kyrgyzstan', 'KG')
INSERT INTO Country VALUES ('Laos', 'LA')
INSERT INTO Country VALUES ('Latvia', 'LV')
INSERT INTO Country VALUES ('Lebanon', 'LB')
INSERT INTO Country VALUES ('Lesotho', 'LS')
INSERT INTO Country VALUES ('Liberia', 'LR')
INSERT INTO Country VALUES ('Libya', 'LY')
INSERT INTO Country VALUES ('Liechtenstein', 'LI')
INSERT INTO Country VALUES ('Lithuania', 'LT')
INSERT INTO Country VALUES ('Luxembourg', 'LU')
INSERT INTO Country VALUES ('Macau', 'MO')
INSERT INTO Country VALUES ('Macedonia', 'MK')
INSERT INTO Country VALUES ('Madagascar', 'MG')
INSERT INTO Country VALUES ('Malawi', 'MW')
INSERT INTO Country VALUES ('Malaysia', 'MY')
INSERT INTO Country VALUES ('Maldives', 'MV')
INSERT INTO Country VALUES ('Mali', 'ML')
INSERT INTO Country VALUES ('Malta', 'MT')
INSERT INTO Country VALUES ('Marshall Islands', 'MH')
INSERT INTO Country VALUES ('Martinique', 'MQ')
INSERT INTO Country VALUES ('Mauritania', 'MR')
INSERT INTO Country VALUES ('Mauritius', 'MU')
INSERT INTO Country VALUES ('Mayotte', 'YT')
INSERT INTO Country VALUES ('Mexico', 'MX')
INSERT INTO Country VALUES ('Micronesia', 'FM')
INSERT INTO Country VALUES ('Moldova', 'MD')
INSERT INTO Country VALUES ('Monaco', 'MC')
INSERT INTO Country VALUES ('Mongolia', 'MN')
INSERT INTO Country VALUES ('Montserrat', 'MS')
INSERT INTO Country VALUES ('Morocco', 'MA')
INSERT INTO Country VALUES ('Mozambique', 'MZ')
INSERT INTO Country VALUES ('Myanmar', 'MM')
INSERT INTO Country VALUES ('Namibia', 'NA')
INSERT INTO Country VALUES ('Nauru', 'NR')
INSERT INTO Country VALUES ('Nepal', 'NP')
INSERT INTO Country VALUES ('Netherlands', 'NL')
INSERT INTO Country VALUES ('Netherlands Antilles', 'AN')
INSERT INTO Country VALUES ('Neutral Zone', 'NT')
INSERT INTO Country VALUES ('New Caledonia', 'NC')
INSERT INTO Country VALUES ('New Zealand (Aotearoa)', 'NZ')
INSERT INTO Country VALUES ('Nicaragua', 'NI')
INSERT INTO Country VALUES ('Niger', 'NE')
INSERT INTO Country VALUES ('Nigeria', 'NG')
INSERT INTO Country VALUES ('Niue', 'NU')
INSERT INTO Country VALUES ('Norfolk Island', 'NF')
INSERT INTO Country VALUES ('Northern Mariana Islands', 'MP')
INSERT INTO Country VALUES ('Norway', 'NO')
INSERT INTO Country VALUES ('Oman', 'OM')
INSERT INTO Country VALUES ('Pakistan', 'PK')
INSERT INTO Country VALUES ('Palau', 'PW')
INSERT INTO Country VALUES ('Panama', 'PA')
INSERT INTO Country VALUES ('Papua New Guinea', 'PG')
INSERT INTO Country VALUES ('Paraguay', 'PY')
INSERT INTO Country VALUES ('Peru', 'PE')
INSERT INTO Country VALUES ('Philippines', 'PH')
INSERT INTO Country VALUES ('Pitcairn', 'PN')
INSERT INTO Country VALUES ('Poland', 'PL')
INSERT INTO Country VALUES ('Portugal', 'PT')
INSERT INTO Country VALUES ('Puerto Rico', 'PR')
INSERT INTO Country VALUES ('Qatar', 'QA')
INSERT INTO Country VALUES ('Reunion', 'RE')
INSERT INTO Country VALUES ('Romania', 'RO')
INSERT INTO Country VALUES ('Russian Federation', 'RU')
INSERT INTO Country VALUES ('Rwanda', 'RW')
INSERT INTO Country VALUES ('S. Georgia & S. Sandwich Isls.', 'GS')
INSERT INTO Country VALUES ('Saint Kitts and Nevis', 'KN')
INSERT INTO Country VALUES ('Saint Lucia', 'LC')
INSERT INTO Country VALUES ('Saint Vincent & the Grenadines', 'VC')
INSERT INTO Country VALUES ('Samoa', 'WS')
INSERT INTO Country VALUES ('San Marino', 'SM')
INSERT INTO Country VALUES ('Sao Tome and Principe', 'ST')
INSERT INTO Country VALUES ('Saudi Arabia', 'SA')
INSERT INTO Country VALUES ('Senegal', 'SN')
INSERT INTO Country VALUES ('Seychelles', 'SC')
INSERT INTO Country VALUES ('Sierra Leone', 'SL')
INSERT INTO Country VALUES ('Singapore', 'SG')
INSERT INTO Country VALUES ('Slovak Republic', 'SK')
INSERT INTO Country VALUES ('Slovenia', 'SI')
INSERT INTO Country VALUES ('Solomon Islands', 'Sb')
INSERT INTO Country VALUES ('Somalia', 'SO')
INSERT INTO Country VALUES ('South Africa', 'ZA')
INSERT INTO Country VALUES ('Spain', 'ES')
INSERT INTO Country VALUES ('Sri Lanka', 'LK')
INSERT INTO Country VALUES ('St. Helena', 'SH')
INSERT INTO Country VALUES ('St. Pierre and Miquelon', 'PM')
INSERT INTO Country VALUES ('Sudan', 'SD')
INSERT INTO Country VALUES ('Suriname', 'SR')
INSERT INTO Country VALUES ('Svalbard and Jan Mayen Islands', 'SJ')
INSERT INTO Country VALUES ('Swaziland', 'SZ')
INSERT INTO Country VALUES ('Sweden', 'SE')
INSERT INTO Country VALUES ('Switzerland', 'CH')
INSERT INTO Country VALUES ('Syria', 'SY')
INSERT INTO Country VALUES ('Taiwan', 'TW')
INSERT INTO Country VALUES ('Tajikistan', 'TJ')
INSERT INTO Country VALUES ('Tanzania', 'TZ')
INSERT INTO Country VALUES ('Thailand', 'TH')
INSERT INTO Country VALUES ('Togo', 'TG')
INSERT INTO Country VALUES ('Tokelau', 'TK')
INSERT INTO Country VALUES ('Tonga', 'TO')
INSERT INTO Country VALUES ('Trinidad and Tobago', 'TT')
INSERT INTO Country VALUES ('Tunisia', 'TN')
INSERT INTO Country VALUES ('Turkey', 'TR')
INSERT INTO Country VALUES ('Turkmenistan', 'TM')
INSERT INTO Country VALUES ('Turks and Caicos Islands', 'TC')
INSERT INTO Country VALUES ('Tuvalu', 'TV')
INSERT INTO Country VALUES ('Uganda', 'UG')
INSERT INTO Country VALUES ('Ukraine', 'UA')
INSERT INTO Country VALUES ('United Arab Emirates', 'AE')
INSERT INTO Country VALUES ('United Kingdom', 'UK')
INSERT INTO Country VALUES ('United States', 'US')
INSERT INTO Country VALUES ('Uruguay', 'UY')
INSERT INTO Country VALUES ('US Minor Outlying Islands', 'UM')
INSERT INTO Country VALUES ('USSR (former)', 'SU')
INSERT INTO Country VALUES ('Uzbekistan', 'UZ')
INSERT INTO Country VALUES ('Vanuatu', 'VU')
INSERT INTO Country VALUES ('Vatican City State (Holy See)', 'VA')
INSERT INTO Country VALUES ('Venezuela', 'VE')
INSERT INTO Country VALUES ('Viet Nam', 'VN')
INSERT INTO Country VALUES ('Virgin Islands (British)', 'VG')
INSERT INTO Country VALUES ('Virgin Islands (U.S.)', 'VI')
INSERT INTO Country VALUES ('Wallis and Futuna Islands', 'WF')
INSERT INTO Country VALUES ('Western Sahara', 'EH')
INSERT INTO Country VALUES ('Yemen', 'YE')
INSERT INTO Country VALUES ('Yugoslavia', 'YU')
INSERT INTO Country VALUES ('Zaire', 'ZR')
INSERT INTO Country VALUES ('Zambia', 'ZM')
INSERT INTO Country VALUES ('Zimbabwe', 'ZW')
INSERT INTO Country VALUES ('Aland Islands', 'AX')
INSERT INTO Country VALUES ('Channel Islands', 'CH')
INSERT INTO Country VALUES ('Guernsey', 'GG')
INSERT INTO Country VALUES ('Isle Of Man', 'IM')
INSERT INTO Country VALUES ('Jersey', 'JE')
INSERT INTO Country VALUES ('Montenegro', 'ME')
INSERT INTO Country VALUES ('Palestinian Territories', 'PS')
INSERT INTO Country VALUES ('Saint Barthelemy', 'BL')
INSERT INTO Country VALUES ('Saint Helena', 'SH')
INSERT INTO Country VALUES ('Saint Martin', 'MF')
INSERT INTO Country VALUES ('Saint Pierre And Miquelon', 'PM')
INSERT INTO Country VALUES ('Serbia', 'RS')
INSERT INTO Country VALUES ('South Georgia & The South Sand', 'GS')
INSERT INTO Country VALUES ('Timor-Leste', 'TL')

TRUNCATE TABLE Manufacturer
GO
INSERT INTO Manufacturer VALUES ('Buick', 226)
INSERT INTO Manufacturer VALUES ('BXR', 226)
INSERT INTO Manufacturer VALUES ('Cadillac', 226)
INSERT INTO Manufacturer VALUES ('Callaway', 226)
INSERT INTO Manufacturer VALUES ('Chevrolet', 226)
INSERT INTO Manufacturer VALUES ('Chrysler', 226)
INSERT INTO Manufacturer VALUES ('DeLorean', 226)
INSERT INTO Manufacturer VALUES ('Detroit Electric', 226)
INSERT INTO Manufacturer VALUES ('Dodge', 226)
INSERT INTO Manufacturer VALUES ('E-Z-GO', 226)
INSERT INTO Manufacturer VALUES ('Falcon', 226)
INSERT INTO Manufacturer VALUES ('Fisker', 226)
INSERT INTO Manufacturer VALUES ('Ford', 226)
INSERT INTO Manufacturer VALUES ('GEM', 226)
INSERT INTO Manufacturer VALUES ('GMC', 226)
INSERT INTO Manufacturer VALUES ('Hennessey', 226)
INSERT INTO Manufacturer VALUES ('Iconic', 226)
INSERT INTO Manufacturer VALUES ('International Harvester', 226)
INSERT INTO Manufacturer VALUES ('Lucra', 226)
INSERT INTO Manufacturer VALUES ('Jeep', 226)
INSERT INTO Manufacturer VALUES ('Lincoln', 226)
INSERT INTO Manufacturer VALUES ('Navistar', 226)
INSERT INTO Manufacturer VALUES ('Panoz', 226)
INSERT INTO Manufacturer VALUES ('Ram', 226)
INSERT INTO Manufacturer VALUES ('Rossion', 226)
INSERT INTO Manufacturer VALUES ('Saleen', 226)
INSERT INTO Manufacturer VALUES ('SSC', 226)
INSERT INTO Manufacturer VALUES ('Tesla', 226)
INSERT INTO Manufacturer VALUES ('Acura', 109)
INSERT INTO Manufacturer VALUES ('Daihatsu', 109)
INSERT INTO Manufacturer VALUES ('Datsun', 109)
INSERT INTO Manufacturer VALUES ('Dome', 109)
INSERT INTO Manufacturer VALUES ('Hino', 109)
INSERT INTO Manufacturer VALUES ('Honda', 109)
INSERT INTO Manufacturer VALUES ('Infiniti', 109)
INSERT INTO Manufacturer VALUES ('Isuzu', 109)
INSERT INTO Manufacturer VALUES ('Lexus', 109)
INSERT INTO Manufacturer VALUES ('Mazda', 109)
INSERT INTO Manufacturer VALUES ('Mitsubishi', 109)
INSERT INTO Manufacturer VALUES ('Mitsuoka', 109)
INSERT INTO Manufacturer VALUES ('Nissan', 109)
INSERT INTO Manufacturer VALUES ('Scion', 109)
INSERT INTO Manufacturer VALUES ('Subaru', 109)
INSERT INTO Manufacturer VALUES ('Suzuki', 109)
INSERT INTO Manufacturer VALUES ('Toyota', 109)
INSERT INTO Manufacturer VALUES ('Yamaha', 109)
INSERT INTO Manufacturer VALUES ('Audi', 82)
INSERT INTO Manufacturer VALUES ('Bitter', 82)
INSERT INTO Manufacturer VALUES ('BMW', 82)
INSERT INTO Manufacturer VALUES ('Büssing', 82)
INSERT INTO Manufacturer VALUES ('Gumpert', 82)
INSERT INTO Manufacturer VALUES ('MAN', 82)
INSERT INTO Manufacturer VALUES ('Mercedes-Benz', 82)
INSERT INTO Manufacturer VALUES ('Multicar', 82)
INSERT INTO Manufacturer VALUES ('Neoplan', 82)
INSERT INTO Manufacturer VALUES ('NSU', 82)
INSERT INTO Manufacturer VALUES ('Opel', 82)
INSERT INTO Manufacturer VALUES ('Porsche', 82)
INSERT INTO Manufacturer VALUES ('Robur', 82)
INSERT INTO Manufacturer VALUES ('Smart', 82)
INSERT INTO Manufacturer VALUES ('Volkswagen', 82)
INSERT INTO Manufacturer VALUES ('Wiesmann', 82)
INSERT INTO Manufacturer VALUES ('Abarth', 107)
INSERT INTO Manufacturer VALUES ('Alfa Romeo', 107)
INSERT INTO Manufacturer VALUES ('Autobianchi', 107)
INSERT INTO Manufacturer VALUES ('Cizeta', 107)
INSERT INTO Manufacturer VALUES ('De Tomaso', 107)
INSERT INTO Manufacturer VALUES ('DR Motor', 107)
INSERT INTO Manufacturer VALUES ('Ferrari', 107)
INSERT INTO Manufacturer VALUES ('Fiat', 107)
INSERT INTO Manufacturer VALUES ('Intermeccanica', 107)
INSERT INTO Manufacturer VALUES ('Lamborghini', 107)
INSERT INTO Manufacturer VALUES ('Lancia', 107)
INSERT INTO Manufacturer VALUES ('Maserati', 107)
INSERT INTO Manufacturer VALUES ('Pagani', 107)
INSERT INTO Manufacturer VALUES ('Siata', 107)
INSERT INTO Manufacturer VALUES ('Vignale', 107)
INSERT INTO Manufacturer VALUES ('AC', 225)
INSERT INTO Manufacturer VALUES ('Allard', 225)
INSERT INTO Manufacturer VALUES ('Alvis', 225)
INSERT INTO Manufacturer VALUES ('Armstrong Siddeley', 225)
INSERT INTO Manufacturer VALUES ('Ascari', 225)
INSERT INTO Manufacturer VALUES ('Aston Martin', 225)
INSERT INTO Manufacturer VALUES ('Austin', 225)
INSERT INTO Manufacturer VALUES ('Austin-Healey', 225)
INSERT INTO Manufacturer VALUES ('BAC', 225)
INSERT INTO Manufacturer VALUES ('Bentley', 225)
INSERT INTO Manufacturer VALUES ('Bowler', 225)
INSERT INTO Manufacturer VALUES ('Bristol', 225)
INSERT INTO Manufacturer VALUES ('British Leyland', 225)
INSERT INTO Manufacturer VALUES ('Caterham', 225)
INSERT INTO Manufacturer VALUES ('Daimler', 225)
INSERT INTO Manufacturer VALUES ('Elva', 225)
INSERT INTO Manufacturer VALUES ('Ginetta', 225)
INSERT INTO Manufacturer VALUES ('GKD', 225)
INSERT INTO Manufacturer VALUES ('Gordon Keeble', 225)
INSERT INTO Manufacturer VALUES ('Grinnall', 225)
INSERT INTO Manufacturer VALUES ('Hillman', 225)
INSERT INTO Manufacturer VALUES ('Humber', 225)
INSERT INTO Manufacturer VALUES ('Jaguar', 225)
INSERT INTO Manufacturer VALUES ('Jensen', 225)
INSERT INTO Manufacturer VALUES ('Jowett', 225)
INSERT INTO Manufacturer VALUES ('Javan', 225)
INSERT INTO Manufacturer VALUES ('Lanchester', 225)
INSERT INTO Manufacturer VALUES ('Land Rover', 225)
INSERT INTO Manufacturer VALUES ('Lister', 225)
INSERT INTO Manufacturer VALUES ('Lotus', 225)
INSERT INTO Manufacturer VALUES ('Marcos', 225)
INSERT INTO Manufacturer VALUES ('McLaren', 225)
INSERT INTO Manufacturer VALUES ('MG', 225)
INSERT INTO Manufacturer VALUES ('Mini', 225)
INSERT INTO Manufacturer VALUES ('Morgan', 225)
INSERT INTO Manufacturer VALUES ('Morris', 225)
INSERT INTO Manufacturer VALUES ('Noble', 225)
INSERT INTO Manufacturer VALUES ('Riley', 225)
INSERT INTO Manufacturer VALUES ('Rolls Royce', 225)
INSERT INTO Manufacturer VALUES ('Rover', 225)
INSERT INTO Manufacturer VALUES ('Singer', 225)
INSERT INTO Manufacturer VALUES ('Standard', 225)
INSERT INTO Manufacturer VALUES ('Sunbeam', 225)
INSERT INTO Manufacturer VALUES ('Triumph', 225)
INSERT INTO Manufacturer VALUES ('Trojan', 225)
INSERT INTO Manufacturer VALUES ('TVR', 225)
INSERT INTO Manufacturer VALUES ('Vauxhall', 225)
INSERT INTO Manufacturer VALUES ('Wolseley', 225)
INSERT INTO Manufacturer VALUES ('Hyundai', 115)
INSERT INTO Manufacturer VALUES ('Kia', 115)
INSERT INTO Manufacturer VALUES ('Proto', 115)
INSERT INTO Manufacturer VALUES ('Samsung', 115)
INSERT INTO Manufacturer VALUES ('SsangYong', 115)
INSERT INTO Manufacturer VALUES ('ABI', 101)
INSERT INTO Manufacturer VALUES ('Ashok Leyland', 101)
INSERT INTO Manufacturer VALUES ('Bajaj', 101)
INSERT INTO Manufacturer VALUES ('Bharat', 101)
INSERT INTO Manufacturer VALUES ('BML', 101)
INSERT INTO Manufacturer VALUES ('Chinkara', 101)
INSERT INTO Manufacturer VALUES ('DC', 101)
INSERT INTO Manufacturer VALUES ('DRDO', 101)
INSERT INTO Manufacturer VALUES ('Eicher', 101)
INSERT INTO Manufacturer VALUES ('Escorts', 101)
INSERT INTO Manufacturer VALUES ('Force', 101)
INSERT INTO Manufacturer VALUES ('Hero', 101)
INSERT INTO Manufacturer VALUES ('Hindustan', 101)
INSERT INTO Manufacturer VALUES ('Hradyesh', 101)
INSERT INTO Manufacturer VALUES ('ICML', 101)
INSERT INTO Manufacturer VALUES ('LML', 101)
INSERT INTO Manufacturer VALUES ('Mahindra', 101)
INSERT INTO Manufacturer VALUES ('Maruti Suzuki', 101)
INSERT INTO Manufacturer VALUES ('Premier', 101)
INSERT INTO Manufacturer VALUES ('REVA', 101)
INSERT INTO Manufacturer VALUES ('Royal Enfield', 101)
INSERT INTO Manufacturer VALUES ('San', 101)
INSERT INTO Manufacturer VALUES ('Swaraj', 101)
INSERT INTO Manufacturer VALUES ('Tata', 101)
INSERT INTO Manufacturer VALUES ('TVS', 101)
INSERT INTO Manufacturer VALUES ('Bharat Benz', 101)
